networks:
  default:
    driver: bridge 


services: 
  gateway:
    image: aykhan151618/baim.ms-api-gateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - default