networks:
  default:
    driver: bridge 


services: 
  gateway:
    image: aykhan151618/baim.ms-api-gateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - identity.api
      - vacancy.api
      - marketing.api
      - personalaccount.api
    networks:
      - default


  identity.api:
    image: aykhan151618/baim.ms-identity
    networks:
      - default

  vacancy.api:
    image: aykhan151618/baim.ms-vacancies
    networks:
      - default

  marketing.api:
    image: aykhan151618/baim.ms-marketing
    networks:
      - default

  personalaccount.api:
    image: aykhan151618/baim.ms-account
    networks:
      - default