networks:
  default:
    driver: bridge
  gateway-network:
    driver: bridge


services: 
  gateway:
    image: aykhan151618/baim.ms-api-gateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - identity.api
      - vacancy.api
      - marketing.api
      - personalaccount.api
    networks:
      - gateway-network


  identity.api:
    image: aykhan151618/baim.ms-identity
    networks:
      - gateway-network

  vacancy.api:
    image: aykhan151618/baim.ms-vacancies
    networks:
      - gateway-network

  marketing.api:
    image: aykhan151618/baim.ms-marketing
    networks:
      - gateway-network

  personalaccount.api:
    image: aykhan151618/baim.ms-account
    networks:
      - gateway-network